const dummyUsers = [
  {
    first_name: 'Hedwig',
    last_name: 'Agates',
    email: 'hagates0@goo.ne.jp',
    gender: 'Female',
    ip_address: '42.159.163.163',
  },
  {
    first_name: 'Nike',
    last_name: 'Beaze',
    email: 'nbeaze1@squidoo.com',
    gender: 'Female',
    ip_address: '203.240.223.44',
  },
  {
    first_name: 'Jacintha',
    last_name: 'Slowgrave',
    email: 'jslowgrave2@usnews.com',
    gender: 'Female',
    ip_address: '202.142.37.71',
  },
  {
    first_name: 'Teirtza',
    last_name: 'Blaine',
    email: 'tblaine3@skyrock.com',
    gender: 'Polygender',
    ip_address: '222.119.28.49',
  },
  {
    first_name: 'Wit',
    last_name: 'Dixson',
    email: 'wdixson4@marketwatch.com',
    gender: 'Male',
    ip_address: '76.172.192.162',
  },
  {
    first_name: 'Vonnie',
    last_name: 'Bernaciak',
    email: 'vbernaciak5@elegantthemes.com',
    gender: 'Female',
    ip_address: '0.228.212.77',
  },
  {
    first_name: 'Meredith',
    last_name: 'Millier',
    email: 'mmillier6@home.pl',
    gender: 'Female',
    ip_address: '178.15.169.149',
  },
  {
    first_name: 'Jean',
    last_name: 'Courtese',
    email: 'jcourtese7@paypal.com',
    gender: 'Male',
    ip_address: '201.52.173.1',
  },
  {
    first_name: 'Fons',
    last_name: 'Masterman',
    email: 'fmasterman8@paginegialle.it',
    gender: 'Male',
    ip_address: '240.147.20.138',
  },
  {
    first_name: 'Steven',
    last_name: 'Rossbrooke',
    email: 'srossbrooke9@chicagotribune.com',
    gender: 'Male',
    ip_address: '85.218.159.71',
  },
  {
    first_name: 'Cristin',
    last_name: 'Nanelli',
    email: 'cnanellia@noaa.gov',
    gender: 'Female',
    ip_address: '200.7.23.17',
  },
  {
    first_name: 'Katheryn',
    last_name: 'Durham',
    email: 'kdurhamb@weather.com',
    gender: 'Female',
    ip_address: '246.104.197.31',
  },
  {
    first_name: 'Maximilianus',
    last_name: 'Pawelke',
    email: 'mpawelkec@princeton.edu',
    gender: 'Male',
    ip_address: '108.184.60.158',
  },
  {
    first_name: 'Phillipp',
    last_name: 'Borgne',
    email: 'pborgned@twitpic.com',
    gender: 'Male',
    ip_address: '10.48.100.241',
  },
  {
    first_name: 'Ric',
    last_name: 'Sesser',
    email: 'rsessere@studiopress.com',
    gender: 'Non-binary',
    ip_address: '23.117.4.93',
  },
  {
    first_name: 'Jacquette',
    last_name: 'Downing',
    email: 'jdowningf@narod.ru',
    gender: 'Female',
    ip_address: '20.31.33.217',
  },
  {
    first_name: 'Tedi',
    last_name: 'Threadgold',
    email: 'tthreadgoldg@cnn.com',
    gender: 'Genderqueer',
    ip_address: '118.149.214.59',
  },
  {
    first_name: 'Papageno',
    last_name: 'Spargo',
    email: 'pspargoh@illinois.edu',
    gender: 'Male',
    ip_address: '59.160.210.81',
  },
  {
    first_name: 'Berkeley',
    last_name: 'Rooson',
    email: 'broosoni@tripadvisor.com',
    gender: 'Male',
    ip_address: '195.70.167.163',
  },
  {
    first_name: 'Hetty',
    last_name: 'Laugharne',
    email: 'hlaugharnej@intel.com',
    gender: 'Female',
    ip_address: '123.38.39.21',
  },
];

export default dummyUsers;
